baseURL = '/'
languageCode = 'en-us'
title = 'Vendee'
theme = "codex"
[params]
  github = "https://github.com/kokkekpek/vendee"
  telegram = "https://t.me/vendeeframework"
  discord = "https://discord.gg/Ef57GCr5"

  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "2 Jan 2006"

  # Titles for your icons (shown as tooltips), and also their display order.
  iconOrder = [
    "GitHub",
    "Telegram",
    "Discord"
  ]

[[menu.main]]
  identifier = "overview"
  name = "Overview"
  title = "Overview"
  url = "/overview"
  weight = -100
[[menu.main]]
  identifier = "initialization"
  name = "Initialization"
  title = "Initialization"
  url = "/initialization"
  weight = -99
[[menu.main]]
  identifier = "Compilation"
  name = "Compilation"
  title = "Compilation"
  url = "/compilation"
  weight = -98
[[menu.main]]
  identifier = "network-and-giver"
  name = "Network and Giver"
  title = "Network and Giver"
  url = "/network-and-giver"
  weight = -97
[[menu.main]]
  identifier = "tests"
  name = "Tests"
  title = "Tests"
  url = "/tests"
  weight = -96
[[menu.main]]
  identifier = "scripts"
  name = "Scripts"
  title = "Scripts"
  url = "/scripts"
  weight = -95
[[menu.main]]
  identifier = "se"
  name = "SE"
  title = "SE"
  url = "/se"
  weight = -94
[[menu.main]]
  identifier = "configuration"
  name = "Configuration"
  title = "Configuration"
  url = "/configuration"
  weight = -93
[[menu.main]]
  identifier = "examples"
  name = "Examples"
  title = "Examples"
  url = "/examples"
  weight = -92
[[menu.main]]
  identifier = "vs-locklift"
  name = "vs Locklift"
  title = "vs Locklift"
  url = "/vs-locklift"
  weight = -91
[[menu.main]]
  identifier = "roadmap"
  name = "Roadmap"
  title = "Roadmap"
  url = "/roadmap"
  weight = -90