version: "3.9"
services:
  nginx:
    image: nginx:1.25.0
    container_name: vendee-docs-nginx
    restart: always
    networks:
      traefik:
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${STATIC_PATH}:/www/data:ro
      - nginx:/var/log/nginx
    labels:
      - traefik.enable=true

      - traefik.http.routers.nginxVendeeDocs.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nginxVendeeDocs.service=nginxVendeeDocs
      - traefik.http.routers.nginxVendeeDocs.entryPoints=http

      - traefik.http.routers.nginxVendeeDocsHttps.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nginxVendeeDocsHttps.service=nginxVendeeDocs
      - traefik.http.routers.nginxVendeeDocsHttps.entryPoints=https
      - traefik.http.routers.nginxVendeeDocsHttps.tls.certResolver=letsEncrypt

      - traefik.http.services.nginxVendeeDocs.loadbalancer.server.port=80

networks:
  traefik:
    external: true
    name: traefik

volumes:
  nginx: