name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  HOST: vendee.top

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Hugo minify
        run: hugo --minify

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.HOST }}
          port: 22
          username: root
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
          source: docker,docker-compose-prod.yaml,.env.prod,public
          target: /srv/${{ github.repository }}
          overwrite: true

      - name: Docker compose up
        uses: appleboy/ssh-action@v0.1.5
        with:
          script: |
            cd /srv/${{ github.repository }}
            docker compose -f docker-compose-prod.yaml --env-file .env.prod pull
            docker compose -f docker-compose-prod.yaml --env-file .env.prod down
            docker compose -f docker-compose-prod.yaml --env-file .env.prod up -d
          host: ${{ env.HOST }}
          port: 22
          username: root
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
